<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251128072108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT NOT NULL, lieu VARCHAR(255) NOT NULL, horaire TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, date DATE NOT NULL, localisation VARCHAR(255) NOT NULL, horaires TIME(0) WITHOUT TIME ZONE NOT NULL, adresse VARCHAR(255) NOT NULL, organisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B26681ED936B2FA ON evenement (organisateur_id)');
        $this->addSql('CREATE TABLE evenement_activite (evenement_id INT NOT NULL, activite_id INT NOT NULL, PRIMARY KEY (evenement_id, activite_id))');
        $this->addSql('CREATE INDEX IDX_3713CEFDFD02F13 ON evenement_activite (evenement_id)');
        $this->addSql('CREATE INDEX IDX_3713CEFD9B0F88B1 ON evenement_activite (activite_id)');
        $this->addSql('CREATE TABLE profil (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pdp VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6D6B297FB88E14F ON profil (utilisateur_id)');
        $this->addSql('CREATE TABLE profil_activite (profil_id INT NOT NULL, activite_id INT NOT NULL, PRIMARY KEY (profil_id, activite_id))');
        $this->addSql('CREATE INDEX IDX_A49C20B8275ED078 ON profil_activite (profil_id)');
        $this->addSql('CREATE INDEX IDX_A49C20B89B0F88B1 ON profil_activite (activite_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, mdp VARCHAR(12) NOT NULL, type VARCHAR(255) NOT NULL, nom_de_scene VARCHAR(255) DEFAULT NULL, pseudo VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, date_de_naissance DATE DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B326E94372 ON utilisateur (siret)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681ED936B2FA FOREIGN KEY (organisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenement_activite ADD CONSTRAINT FK_3713CEFDFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_activite ADD CONSTRAINT FK_3713CEFD9B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profil ADD CONSTRAINT FK_E6D6B297FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE profil_activite ADD CONSTRAINT FK_A49C20B8275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profil_activite ADD CONSTRAINT FK_A49C20B89B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681ED936B2FA');
        $this->addSql('ALTER TABLE evenement_activite DROP CONSTRAINT FK_3713CEFDFD02F13');
        $this->addSql('ALTER TABLE evenement_activite DROP CONSTRAINT FK_3713CEFD9B0F88B1');
        $this->addSql('ALTER TABLE profil DROP CONSTRAINT FK_E6D6B297FB88E14F');
        $this->addSql('ALTER TABLE profil_activite DROP CONSTRAINT FK_A49C20B8275ED078');
        $this->addSql('ALTER TABLE profil_activite DROP CONSTRAINT FK_A49C20B89B0F88B1');
        $this->addSql('DROP TABLE activite');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE evenement_activite');
        $this->addSql('DROP TABLE profil');
        $this->addSql('DROP TABLE profil_activite');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
